### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by Pierstoval** [Jomcraft-Network/ServerPassword#2]
Hey @PT400C, what do you need to make it compatible with the freshly released 1.18 version? 😉

**Comment by PT400C** [comment]
Hey :)

I might update it around the turn of the year. Should't take too long.

**Comment by PT400C** [comment]
Support for 1.18.x has been added and should be live on CurseForge within the next few minutes. Commit for reference: https://github.com/Jomcraft-Network/ServerPassword/commit/a20a3755f648f789015503e759f0a683284c6f46

Cheers and happy new year in advance! 😄 

PT400C

**Comment by Pierstoval** [comment]
Thanks a lot! Will check it out 👍
